name: mavis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - seaborn
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - umap-learn
  - black
  - flake8
  - isort
  - pip:
    - python-dotenv
    - jupyter-black
    - plotly
    #- tsnecuda
    - vizdataquality
    - awscli
    - mkdocs
    - -e .